#!/usr/bin/env bash

top -bn1 | grep '%Cpu(s)' | cut -d ',' -f 4 | awk '{print "Cpu usage:\t" 100-$1"%"}'

echo "-------"

free | grep 'Mem:' | awk '{printf "FreeMem:\t%s\nUsedMem:\t%s\nMemUsage:\t%s%\n", $4, $3, 100*($3/$4)}'

echo "-------"

df -h | grep -w '/' | awk '{printf "FreeStorage:\t%s\nUsedStorage:\t%s\nStorageUsage:\t%s%\n", $3, $4, 100*($3/$4)}'

echo "-------"

echo "Top 5 Cpu Usage"
ps auxk-%cpu | head -n 6 | awk '{print $1 "\t" $2 "\t" $3 "\t" $11}'

echo "-------"

echo "Top 5 Mem Usage"
ps auxk-%mem | head -n 6 | awk '{print $1 "\t" $2 "\t" $4 "\t" $11}'
