#!/bin/bash

echo "Top 5 IP addresses with the most requests:"
awk '{print $1}' "$1"| sort | uniq -c | sort -nr | head -n 5 | awk '{print $2 " - " $1 " requests"}'

echo -e "\nTop 5 most requested paths:"
awk '{print $7}' "$1" | sort | uniq -c | sort -nr | head -n 5 | awk '{print $2 " - " $1 " requests"}'

echo -e "\nTop 5 response status codes:"
grep -o ' [1-5][0-9][0-9] ' "$1" | sort | uniq -c | sort -nr | head -n 5 | awk '{print $2 " - " $1 " requests"}'

echo -e "\nTop 5 User Agents:"
awk -F'"' '{print $6}' "$1" | sort | uniq -c | sort -nr | head -n 5 | awk '{for(i=2;i<=NF;i++) printf "%s%s", $i, (i==NF ? " - "$1" requests\n" : OFS)}'
